env:
  global:
    - DISPLAY=":99.0"
notifications:
  recipients:
    - ruby-gnome2-cvs@lists.sourceforge.net
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
#  allow_failures:
#    - rvm: ruby-head
  fast_finish: true
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
